import type { User, Conversation, Message, Post, Comment } from '@/types'

const now = new Date()
const h = (hours: number) => new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString()
const expiry = (hours: number) => new Date(now.getTime() + (24 - hours) * 60 * 60 * 1000).toISOString()

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    email: 'alex@shredder.app',
    name: 'Alex Rivera',
    username: 'alexrivera',
    avatar_url: null,
    is_online: true,
    last_seen: now.toISOString(),
    bio: 'Product designer & coffee enthusiast',
    role: 'admin',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'u2',
    email: 'julian@shredder.app',
    name: 'Julian Casablancas',
    username: 'juliancasa',
    avatar_url: null,
    is_online: true,
    last_seen: now.toISOString(),
    bio: 'Lead Product Designer @ DesignCo',
    role: 'user',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'u3',
    email: 'mia@shredder.app',
    name: 'Mia Khalil',
    username: 'miakhalil',
    avatar_url: null,
    is_online: false,
    last_seen: h(3),
    bio: 'Frontend engineer • TypeScript lover',
    role: 'user',
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'u4',
    email: 'arlo@shredder.app',
    name: 'Arlo Parks',
    username: 'arloparks',
    avatar_url: null,
    is_online: false,
    last_seen: h(48),
    bio: 'Music & tech',
    role: 'user',
    created_at: '2024-02-15T00:00:00Z',
  },
  {
    id: 'u5',
    email: 'jordan@shredder.app',
    name: 'Jordan Blake',
    username: 'jordanblake',
    avatar_url: null,
    is_online: true,
    last_seen: now.toISOString(),
    bio: 'Full-stack dev',
    role: 'user',
    created_at: '2024-03-01T00:00:00Z',
  },
]

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'c1',
    type: 'direct',
    created_by: 'u1',
    created_at: h(5),
    unread_count: 0,
    participants: [
      { user_id: 'u1', conversation_id: 'c1', joined_at: h(5), is_muted: false, user: MOCK_USERS[0] },
      { user_id: 'u2', conversation_id: 'c1', joined_at: h(5), is_muted: false, user: MOCK_USERS[1] },
    ],
    last_message: {
      id: 'm4',
      conversation_id: 'c1',
      sender_id: 'u1',
      content: 'Check this out—testing the glassmorphism on the mobile cards. It pops!',
      type: 'text',
      status: 'seen',
      is_anonymous: false,
      created_at: h(0.5),
      expires_at: expiry(0.5),
    },
  },
  {
    id: 'c2',
    type: 'direct',
    created_by: 'u3',
    created_at: h(20),
    unread_count: 3,
    participants: [
      { user_id: 'u1', conversation_id: 'c2', joined_at: h(20), is_muted: false, user: MOCK_USERS[0] },
      { user_id: 'u3', conversation_id: 'c2', joined_at: h(20), is_muted: false, user: MOCK_USERS[2] },
    ],
    last_message: {
      id: 'm10',
      conversation_id: 'c2',
      sender_id: 'u3',
      content: "I'll send the file over shortly. Thanks!",
      type: 'text',
      status: 'delivered',
      is_anonymous: false,
      created_at: h(18),
      expires_at: expiry(18),
    },
  },
  {
    id: 'c3',
    type: 'direct',
    created_by: 'u4',
    created_at: h(72),
    unread_count: 0,
    participants: [
      { user_id: 'u1', conversation_id: 'c3', joined_at: h(72), is_muted: false, user: MOCK_USERS[0] },
      { user_id: 'u4', conversation_id: 'c3', joined_at: h(72), is_muted: false, user: MOCK_USERS[3] },
    ],
    last_message: {
      id: 'm20',
      conversation_id: 'c3',
      sender_id: 'u4',
      content: 'The conference was amazing...',
      type: 'text',
      status: 'seen',
      is_anonymous: false,
      created_at: h(50),
      expires_at: expiry(50),
    },
  },
  {
    id: 'c4',
    type: 'group',
    name: 'Product Team',
    created_by: 'u5',
    created_at: h(100),
    unread_count: 0,
    participants: [
      { user_id: 'u1', conversation_id: 'c4', joined_at: h(100), is_muted: false, user: MOCK_USERS[0] },
      { user_id: 'u2', conversation_id: 'c4', joined_at: h(100), is_muted: false, user: MOCK_USERS[1] },
      { user_id: 'u5', conversation_id: 'c4', joined_at: h(100), is_muted: false, user: MOCK_USERS[4] },
    ],
    last_message: {
      id: 'm30',
      conversation_id: 'c4',
      sender_id: 'u5',
      content: "Let's push the build tonight.",
      type: 'text',
      status: 'delivered',
      is_anonymous: false,
      created_at: h(24),
      expires_at: expiry(24),
    },
  },
]

export const MOCK_MESSAGES: Record<string, Message[]> = {
  c1: [
    {
      id: 'm1',
      conversation_id: 'c1',
      sender_id: 'u2',
      content: 'Hey Alex! Have you had a chance to look at the new design system components I shared this morning?',
      type: 'text',
      status: 'seen',
      is_anonymous: false,
      created_at: h(2),
      expires_at: expiry(2),
    },
    {
      id: 'm2',
      conversation_id: 'c1',
      sender_id: 'u1',
      content: 'Just going through them now. The tonal layering approach is really slick. It feels much more premium than the previous version.',
      type: 'text',
      status: 'seen',
      is_anonymous: false,
      created_at: h(1.9),
      expires_at: expiry(1.9),
    },
    {
      id: 'm3',
      conversation_id: 'c1',
      sender_id: 'u2',
      content: 'Glad you like it! I was worried the "no-line" rule might make it feel too open, but the background shifts seem to hold the structure well.',
      type: 'text',
      status: 'seen',
      is_anonymous: false,
      created_at: h(1.8),
      expires_at: expiry(1.8),
    },
    {
      id: 'm3b',
      conversation_id: 'c1',
      sender_id: 'u2',
      content: 'Let me know if you see any accessibility issues with the ghost borders.',
      type: 'text',
      status: 'seen',
      is_anonymous: false,
      created_at: h(1.7),
      expires_at: expiry(1.7),
    },
    {
      id: 'm4',
      conversation_id: 'c1',
      sender_id: 'u1',
      content: 'Check this out—testing the glassmorphism on the mobile cards. It pops!',
      type: 'text',
      status: 'seen',
      is_anonymous: false,
      created_at: h(0.5),
      expires_at: expiry(0.5),
    },
  ],
  c2: [
    {
      id: 'm10',
      conversation_id: 'c2',
      sender_id: 'u3',
      content: "I'll send the file over shortly. Thanks!",
      type: 'text',
      status: 'delivered',
      is_anonymous: false,
      created_at: h(18),
      expires_at: expiry(18),
    },
  ],
}

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    author_id: 'u2',
    content: 'Just shipped the new dark mode for Shredder! 🚀 The glassmorphism effects look incredible. Check it out and let me know what you think.',
    is_anonymous: false,
    created_at: h(2),
    expires_at: expiry(2),
    like_count: 12,
    comment_count: 3,
    liked_by_me: true,
    author: MOCK_USERS[1],
    comments: [
      {
        id: 'cm1',
        post_id: 'p1',
        author_id: 'u3',
        content: 'This looks amazing! 🔥',
        is_anonymous: false,
        created_at: h(1.5),
        expires_at: expiry(1.5),
        author: MOCK_USERS[2],
      },
      {
        id: 'cm2',
        post_id: 'p1',
        author_id: 'u5',
        content: 'Great work Julian! The tonal layers really tie it together.',
        is_anonymous: false,
        created_at: h(1),
        expires_at: expiry(1),
        author: MOCK_USERS[4],
      },
    ],
  },
  {
    id: 'p2',
    author_id: 'u1',
    content: 'Hot take: the best messaging apps are the ones that respect your privacy. Everything should self-destruct by default.',
    is_anonymous: false,
    created_at: h(5),
    expires_at: expiry(5),
    like_count: 8,
    comment_count: 1,
    liked_by_me: false,
    author: MOCK_USERS[0],
  },
  {
    id: 'p3',
    author_id: 'u4',
    content: 'Does anyone have recommendations for a good TypeScript-first state management library? Zustand vs Jotai?',
    is_anonymous: true,
    created_at: h(8),
    expires_at: expiry(8),
    like_count: 5,
    comment_count: 0,
    liked_by_me: false,
  },
]

export const CURRENT_USER = MOCK_USERS[0]
